server:
  port: 8200
spring:
  application:
    name: eureka-consumer
eureka:
  instance:
    prefer-ip-address: true #使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  security:
    enabled: false #actuator 设置为允许访问
endpoints:
  beans:
    id: mybean  #定制端点的属性